### ISSUE TITLE
Lowercase letters in config-template.yml

### ISSUE THREAD

**Issue by Davcode1234** [Problematy/goodmap#32]
``` 
# -- Basic app configuration
app_name: My awesome goodmap application

## -- Flask's SECRET_KEY. In production environment you should set it and keep secret.
## -- Ref: https://flask.palletsprojects.com/en/2.1.x/config/
# flask_secretkey: YOU SHOULD CHANGE IT!!!

## -- Languages supported by application
## -- First language would be used as default
languages:
  - en
#  - pl

# -- Database configuration

## -- DB stored in simple json file
db:
  type: json_file
  data_file_path: data.json

## -- DB stored in google cloud storage as json.
# db:
#   type: google_hosted_json_file
#   bucket_name: good-map
#   source_blob_name: data.json

## -- List of overwrites for routes. Useful in frontend development.
route_overwrites:
  /static/map.js: https://cdn.jsdelivr.net/npm/@problematy/goodmap@0.1.2
```
Keys in this file should be uppercase as it's in e2e_test_config.yml file
